---
dependency:
  name: galaxy
  enabled: false
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos8
    image: jrei/systemd-centos:8
    command: /usr/sbin/init
    tmpfs:
     - /run
     - /tmp
     - /var/run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml
verifier:
  name: ansible
